### ISSUE TITLE
Potential bug when `check_arg()` stretched over multiple lines

### ISSUE THREAD

**Issue by s3alfisc** [lrberge/dreamerr#1]
Hi Laurent, 

I am currently working towards submitting `fwildclusterboot` to a review process at `ropensci`, which requires to split long lines of code into multiple lines (they enforce a line limit to enhance code readability). While doing so, I stumbled over a small potential bug of `dreamerr::check_arg()` with `charin` - namely, when I tried to split a line argument check over multiple lines, `dreamerr` would complain because it would include the whitespace into the charin() statement. It's quite likely that this is not a bug, but a design choice, but I thought I'd report it nevertheless :) 

Here is a reproducible example: 

```
example_fun <- function(arg){
  
  dreamerr::check_arg(arg, "charin(A, B, 
                      C, D)")
  
  arg
  
}

example_fun("A")
example_fun("B")
example_fun("C")
Error: in example_fun("C"): Argument 'arg' must be a single character
equal to 'A', 'B', '
                      C' or 'D'. Problem: the value 'C' doesn't match any choice.
```
Best, Alex

**Comment by lrberge** [comment]
Hi Alex and sorry for the late reply!
You have the argument `.choices` for that:
```R
check_arg(arg, "charin", .choices = c(A, B, 
                                      C, D))
```

By the way, if you need an urgent fix: better drop me a line directly I'm more reactive via email.

**Comment by s3alfisc** [comment]
Excellent, and thanks! =)
